### PR TITLE
Fix feeshare, add TokenFactory & IBCRouter

### PR DESCRIPTION
**Pull request by reecepbcups**
So I forgot to npm run build:ts on that last one, my bad. Still very new to the Ts world

tested this time locally (learned you can absolute path to the local module :D). So stoked to have learned this

Picture proof it works this time & signed + broadcasted
image

https://www.mintscan.io/juno/txs/8F09B879470C99E6319F5AEB4732D5C57C0E4F6FAFA332EC9E10E8D0AD01C885

### CODE REVIEW

**Comment by reecepbcups** [comment]
I'm going to get in a tokenfactory PR tomorrow then will tag dan

**Comment by reecepbcups** [comment]
TF works (both signing and queries)
image

**Comment by reecepbcups** [comment]
@pyramation sorry about this - is fixed now :) absolutely love this repo, simplifies my code a ton. Amazing work

**Review by JakeHartnell — APPROVED** [review]
LGTM

**Pull request merged**
